version: '3.7'

services:
  git:
    image: ${SERVICE_IMAGE_REGISTRY}/whatwewant/gogs:${SERVICE_GIT_VERSION}
    # ports:
    #   - 8080:3000
    #   - 10022:22
    environment:
      TZ: Asia/Shanghai
      COMPANY: ${SERVICE_GIT_COMPANY}
      # PORT: 8080
      ROOT_URL: ${SERVICE_GIT_ROOT_URL}
      SECRET_KEY: ${SERVICE_GIT_SECRET_KEY}
      #
      MAIL_ENABLE: '${SERVICE_GIT_MAIL_ENABLE}'
      MAIL_HOST: ${SERVICE_GIT_MAIL_HOST}
      MAIL_PORT: ${SERVICE_GIT_MAIL_PORT}
      MAIL_USERNAME: ${SERVICE_GIT_MAIL_USERNAME}
      MAIL_PASSWORD: ${SERVICE_GIT_MAIL_PASSWORD}
      #
      OAUTH2_ENABLE: ${SERVICE_GIT_OAUTH2_ENABLE}
      OAUTH2_SERVER_URL: ${SERVICE_GIT_OAUTH2_SERVER_URL}
      OAUTH2_CLIENT_ID: ${SERVICE_GIT_OAUTH2_CLIENT_ID}
      OAUTH2_CLIENT_SECRET: ${SERVICE_GIT_OAUTH2_CLIENT_SECRET}
      #
      DISABLE_GRAVATAR: true
      # Database
      DB_TYPE: ${SERVICE_GIT_DB_TYPE}
      DB_HOST: ${SERVICE_GIT_DB_HOST}
      DB_PORT: ${SERVICE_GIT_DB_PORT}
      DB_USERNAME: ${SERVICE_GIT_DB_USERNAME}
      DB_PASSWORD: ${SERVICE_GIT_DB_PASSWORD}
      DB_NAME: ${SERVICE_GIT_DB_NAME}
    volumes:
      - ${SERVICE_DATA}:/data

networks:
  default:
    external: true
    name: compose-ingress
